steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/terraform-429505/mynewapp:${_COMMIT_SHA}', '.']

  # Push the image to the Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/terraform-429505/mynewapp:${_COMMIT_SHA}']

  # Apply the delivery pipeline and target configurations
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    dir: 'clouddeploy-config'
    args:
    - bash
    - -c
    - |
      gcloud deploy apply --file=delivery-pipeline.yaml --region=asia-east1
      gcloud deploy apply --file=target-test.yaml --region=asia-east1
      gcloud deploy apply --file=target-staging.yaml --region=asia-east1
      gcloud deploy apply --file=target-prod.yaml --region=asia-east1

  # Create a release
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
    - 'deploy'
    - 'releases'
    - 'create'
    - 'release-${_SHORT_SHA}'
    - '--delivery-pipeline=demo-pipeline'
    - '--region=asia-east1'
    - '--annotations=commitId=${_REVISION_ID}'
    - '--source=.' 
    - '--skaffold-file=./app-config/skaffold.yaml'
    - '--images=my-service=gcr.io/terraform-429505/mynewapp:${_SHORT_SHA}'


  # Deploy to test environment
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
    - 'deploy'
    - 'releases'
    - 'promote'
    - '--release=release-${_SHORT_SHA}'
    - '--delivery-pipeline=demo-pipeline'
    - '--region=asia-east1'
    - '--to-target=test-cloudrun'

  # Deploy to staging environment
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
    - 'deploy'
    - 'releases'
    - 'promote'
    - '--release=release-${_SHORT_SHA}'
    - '--delivery-pipeline=demo-pipeline'
    - '--region=asia-east1'
    - '--to-target=staging-cloudrun'

  # Deploy to production environment
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
    - 'deploy'
    - 'releases'
    - 'promote'
    - '--release=release-${_SHORT_SHA}'
    - '--delivery-pipeline=demo-pipeline'
    - '--region=asia-east1'
    - '--to-target=prod-cloudrun'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
