apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
  name: demo-pipeline
description: Deployment pipeline for hello-js
serialPipeline:
  stages:
    - targetId: test-cloudrun
      profiles: [test]
    - targetId: staging-cloudrun
      profiles: [staging]
    - targetId: prod-cloudrun
      profiles: [prod]