apiVersion: skaffold/v3
kind: Config
metadata:
  name: hello-js
# build:
#   artifacts:
#     - image: hello-app
#       context: hello-app
#   googleCloudBuild:
#     projectId: terraform-429505
#     serviceAccount: projects/terraform-429505/serviceAccounts/cd-tut-run-build-sa@terraform-429505.iam.gserviceaccount.com
deploy:
  cloudrun: {}
profiles:
  - name: test
    manifests:
      rawYaml:
        - test.yaml
  - name: staging
    manifests:
      rawYaml:
        - staging.yaml
  - name: prod
    manifests:
      rawYaml:
        - prod.yaml